#!/usr/bin/env python3
"""Render card navigation and build the deterministic Writing Plans manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import posixpath
from pathlib import Path
import sys
from urllib.parse import quote

from _writing_reference_cards import atomic_write, build_manifest, canonical_json_bytes, discover_cards, issue_payload, replace_navigation


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "registries" / "reference-cards.manifest.json"
SUPPORT_MAP = ROOT / "references" / "package-support-map.md"
SUPPORT_ROOTS = ("references", "registries", "schemas", "scripts", "templates", "operator", "tests")
SUPPORT_MAP_RELATIVE = SUPPORT_MAP.relative_to(ROOT).as_posix()
MANIFEST_RELATIVE = MANIFEST.relative_to(ROOT).as_posix()


def discover_support_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for top_level in SUPPORT_ROOTS:
        support_root = root / top_level
        if support_root.is_symlink():
            raise ValueError(f"support root must not be a symlink: {top_level}")
        if not support_root.exists():
            continue
        if not support_root.is_dir():
            raise ValueError(f"support root must be a directory: {top_level}")
        for path in support_root.rglob("*"):
            relative = path.relative_to(root)
            if "__pycache__" in relative.parts or path.suffix in {".pyc", ".pyo"}:
                continue
            if path.is_symlink():
                raise ValueError(f"support inventory entry must not be a symlink: {relative.as_posix()}")
            if path.is_file() and relative.as_posix() != SUPPORT_MAP_RELATIVE:
                files.append(path)
    return sorted(files, key=lambda path: path.relative_to(root).as_posix())


def build_support_map(root: Path, byte_overrides: dict[str, bytes] | None = None) -> bytes:
    overrides = byte_overrides or {}
    files = discover_support_files(root)
    populated_roots = [
        top_level for top_level in SUPPORT_ROOTS
        if any(path.relative_to(root).parts[0] == top_level for path in files)
    ]
    lines = [
        "# Package Support Map",
        "",
        "<!-- Generated by scripts/build_reference_manifest.py; do not edit. -->",
        "",
        "## Contents",
        "",
    ]
    lines.extend(f"- [{top_level}](#{top_level})" for top_level in populated_roots)
    for top_level in populated_roots:
        lines.extend(("", f"## {top_level}", ""))
        for path in files:
            relative = path.relative_to(root).as_posix()
            if path.relative_to(root).parts[0] != top_level:
                continue
            digest = hashlib.sha256(overrides.get(relative, path.read_bytes())).hexdigest()
            target = posixpath.relpath(relative, start="references")
            lines.append(f"- [`{relative}` · `sha256:{digest}`]({quote(target, safe='/._-')})")
    return ("\n".join(lines) + "\n").encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--render", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.render:
            for card in discover_cards(ROOT):
                rendered = replace_navigation(card)
                if rendered != card.raw:
                    atomic_write(card.path, rendered)
        manifest, issues = build_manifest(ROOT)
        if issues:
            print(json.dumps({"ok": False, "issues": issue_payload(issues)}, ensure_ascii=False, indent=2))
            return 2
        generated = canonical_json_bytes(manifest)
        support_generated = build_support_map(ROOT, {MANIFEST_RELATIVE: generated})
        if args.check:
            if not MANIFEST.is_file() or MANIFEST.is_symlink() or MANIFEST.read_bytes() != generated:
                print(json.dumps({"ok": False, "error": "MANIFEST_STALE", "path": str(MANIFEST)}, indent=2))
                return 2
            if not SUPPORT_MAP.is_file() or SUPPORT_MAP.is_symlink() or SUPPORT_MAP.read_bytes() != support_generated:
                print(json.dumps({"ok": False, "error": "SUPPORT_MAP_STALE", "path": str(SUPPORT_MAP)}, indent=2))
                return 2
        else:
            atomic_write(MANIFEST, generated)
            atomic_write(SUPPORT_MAP, support_generated)
    except (OSError, ValueError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False, indent=2))
        return 2
    print(json.dumps({
        "ok": True,
        "path": str(MANIFEST),
        "support_map": str(SUPPORT_MAP),
        "cards": len(manifest["cards"]),
        "support_files": len(discover_support_files(ROOT)),
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
