#!/usr/bin/env python3
"""Render card navigation and build the deterministic SQW card manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from _workflow_reference_cards import atomic_write, build_manifest, canonical_json_bytes, discover_cards, issue_payload, replace_navigation


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "registries" / "reference-cards.manifest.json"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare generated bytes without writing")
    parser.add_argument("--render", action="store_true", help="regenerate body navigation from frontmatter first")
    args = parser.parse_args(argv)
    try:
        if args.render:
            for card in discover_cards(ROOT):
                rendered = replace_navigation(card)
                if rendered != card.raw:
                    atomic_write(card.path, rendered)
        manifest, issues = build_manifest(ROOT)
        if issues:
            print(json.dumps({"ok": False, "issues": issue_payload(issues)}, ensure_ascii=False, indent=2))
            return 2
        generated = canonical_json_bytes(manifest)
        if args.check:
            if not MANIFEST.is_file() or MANIFEST.is_symlink() or MANIFEST.read_bytes() != generated:
                print(json.dumps({"ok": False, "error": "MANIFEST_STALE", "path": str(MANIFEST)}, indent=2))
                return 2
        else:
            atomic_write(MANIFEST, generated)
    except (OSError, ValueError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False, indent=2))
        return 2
    print(json.dumps({"ok": True, "path": str(MANIFEST), "cards": len(manifest["cards"])}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
